### ISSUE TITLE
64 Enigma + Chosen interaction bug

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#113]
BUG: When fighting the Chosen with Enigma running, playing a Dazed puts 2 Dazed into your draw pile. It should only be 1 Dazed (because playing the card, which is not an attack, will trigger Hex).

**Comment by daviscook477** [comment]
This is the weirdest bug I've seen yet. Totally reproducible but I have no idea why it's happening

**Comment by daviscook477** [comment]
Workaround made

**Comment by Lunaraia** [comment]
my guess as to whats happening is that you are playing the daze, which is technically playing a non attack card, then enigmas effect is "played" and this trigger another daze, since it's not an attack, that reminds me Dead Branch does the same thing, it coughs up 2 cards when playing a daze, so I guessing it's the same thing there.

**Comment by daviscook477** [comment]
Thanks for the heads up @Lunaraia . @gskleres since it looks like this is base game issue, can I revert my (kinda sketchy) "bug-fix" and just leave this as an intentional interaction?

**Comment by gskleres** [comment]
@daviscook477 so if I understand correctly, Enigma makes it so that Dazed is playable, and when you play it then behind the scenes it makes a new card that gets played?

**Comment by daviscook477** [comment]
See I don't really understand what's going on behind the scenes

**Comment by gskleres** [comment]
Tested by @fiiiiilth who confirmed working
