### ISSUE TITLE
Thoughts on the card changes...

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#121]
Soo... the changes to the cards... kiiinda broke Daze decks, as in something is really off here, I am not sure why Dazes are suddenly dealing insane amounts of damage, as in 42 per Daze played, as that's what happens after just a few Enigmas being played, Nexus is also insanely powerful, to the point of being borderline broken if you decide to abuse it, in one match I managed to duplicate enough cards that when i played my (by then about 1 of 40) Meteor Showers everything died, Daze is jsut ridiculously powerful with the new changes and you might wanna power them down a bit.

Self Status....

Soo Flicker+, Force Ripple into Vacum is just a TEEENY bit too powerful, in my test run of self status I had Donau and Deca as the final bosses, my turn once consisted of playing: Flicker+, then Zenith+ (6 energy) followed by another Zenith (10 Energy), then I played Force Ripple, which got doubled due to Necronomicon, Deca was dead at this point, then i played Overload and pointed Vacuum at Donau, who took  600 X 9 = 5400 damage, the reason for this plum ridiculous amount of damage is because Force Ripple adds the Weak, Vulnerable and Frail effect to every hit in the combo, in this case it hit 20 times because of Necronomicon multiplying it so it added 10 Frail, Weak and Vulnerable 20 times for a grand total of 200 each, which then got removed and multiplied by 9 because of the reversed Weak and then slammed into Donau and I seriously don't think that was the intent.

**Comment by gskleres** [comment]
Thanks for the write up!

* Multiple enigmas is probably a bug applying your Str once per enigma. It should just be once ever and each Enigma increases damage by 1. So for example, if you had 3 Str and played Enigma twice, a Dazed would be playable for 5 (3 + 2) damage.
* The combo you had with Necronomicon actually sounds pretty reasonable to be honest. You had multiple rare/uncommon cards all drawn together at the right time. It's not out of the realm of what Ironclad and Silent can do with their cards.
* That is a bug with Force Ripple. You should only be gaining the Frail, Weak, and Vulnerable one time. So when that bug is fixed, the 5400 damage would actually be 270 damage, which seems much more reasonable and within the realm of normal high-roll possibilities after good deck building. :)

**Comment by daviscook477** [comment]
@gskleres these interactions are getting weird. It's really hard to tell when strength and dex should or should not apply to seeker cards.

**Comment by daviscook477** [comment]
@Lunaraia that was totally a bug with force ripple. It was giving X^2 stacks instead of X stacks.

**Comment by daviscook477** [comment]
Also @Lunaraia I can't reproduce the Dazed + Enigma issue. In my testing Scenario I have 3 stacks of enigma and 6 stacks of strength (from casting flex 3 times) and what happens is each Dazed that I play deals 9 damage to all enemies and gives me 3 block. This is the expected behavior.

**Comment by Lunaraia** [comment]
I am not sure whats going on then I had a whole bunch of stuff going gimmie a bit and I will see if I can reproduce it

**Comment by daviscook477** [comment]
@Lunaraia gotcha. Makes sense. If we're going to keep it scaling with strength/dex I'm going to add it to the tooltip and card description.

**Comment by daviscook477** [comment]
Added to the description for Enigma and the other bugs are fixed
